# The following redirect is intended for use with most SPAs that handle
# routing internally.

[build]
  command="ng build"
  publish="dist/project-management-app"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:4000/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "*"
